export const PASTORDERS=[
    {
        id: 'bd7acbea-c1b1-46c2-aed5-3ad53abb28ba',
        ordernum:'1000',
        meal: 'Poutine',
        extras:'Chicken Biryani,sambhar,Masala dosa',
        receiver:'Michael Jackson',
        recieverAddress:'Torronto',
        expected_time:'12:00 PM',
        status:'Delivered',
        delivery_date:'20 Oct',
        avatar_url:'https://icons.iconarchive.com/icons/diversity-avatars/avatars/128/muslim-man-icon.png',
        mealtype:'nonveg',
        extratype:'nonveg'
      },
      {
        id: '3ac68afc-c605-48d3-a4f8-fbd91aa97f63',
        ordernum:'1001',
        meal: 'Poutine Margharetta',
        extras:'Naan',
        receiver:'Peter James',
        recieverAddress:'Delhi',
        expected_time:'12:10 PM',
        status:'Cancelled',
        delivery_date:'20 Oct',
        avatar_url:'https://icons.iconarchive.com/icons/diversity-avatars/avatars/128/mahatma-gandhi-icon.png',
        mealtype:'nonveg',
        extratype:'veg'
      },
      {
        id: '58694a0f-3da1-471f-bd96-145571e29d72',
        ordernum:'1002',
        meal: 'Sheer khurma ',
        extras:'Brocolli salad',
        receiver:'Stephen Grider',
        recieverAddress:'Ontario',
        expected_time:'12:20 PM',
        status:'Delivered',
        delivery_date:'20 Oct',
        avatar_url:'https://icons.iconarchive.com/icons/diversity-avatars/avatars/128/andy-warhol-icon.png',
        mealtype:'veg',
        extratype:'nonveg'
    
      },
      {
        id: '58695a0f-3da1-471f-bd96-145571e29d72',
        ordernum:'1802',
        meal: 'Sheer khurma ',
        extras:'Brocolli salad',
        receiver:'Stephen Grider',
        recieverAddress:'Pensyllvania',
        expected_time:'20:00 PM',
        status:'Delivered',
        delivery_date:'20 Oct',
        avatar_url:'https://icons.iconarchive.com/icons/diversity-avatars/avatars/128/barack-obama-icon.png',
        mealtype:'veg',
        extratype:'veg'
      },
      {
        id: '58794a0f-3da1-471f-bd96-145571e29d72',
        ordernum:'1006',
        meal: 'Sheer khurma ',
        extras:'Brocolli sala',
        receiver:'Stephen Grider',
        recieverAddress:'Washington Dc',
        expected_time:'22:00 PM',
        status:'Delivered',
        delivery_date:'19 Oct',
        avatar_url:'https://icons.iconarchive.com/icons/diversity-avatars/avatars/128/indian-man-icon.png',
        mealtype:'nonveg',
        extratype:'veg'
      },
      {
        id: 'bd7acbea-c1b1-46c2-aed5-3ad53adsa28ba',
        ordernum:'1007',
        meal: 'Poutine',
        extras:'Chicken Biryani,sambhar,Masala dosa',
        receiver:'Michael Jackson',
        recieverAddress:'Torronto',
        expected_time:'21:00 PM',
        delivery_date:'19 Oct',
        status:'Cancelled',
        avatar_url:'https://icons.iconarchive.com/icons/diversity-avatars/avatars/128/muslim-man-icon.png',
        mealtype:'nonveg',
        extratype:'nonveg'
      },
      {
        id: '3ac68afc-c605-48d3-sadf8-fbd91aa97f63',
        ordernum:'1008',
        meal: 'Poutine Margharetta',
        extras:'Naan',
        receiver:'Peter James',
        recieverAddress:'Delhi',
        expected_time:'20:20 PM',
        status:'Delivered',
        delivery_date:'19 Oct',
        avatar_url:'https://icons.iconarchive.com/icons/diversity-avatars/avatars/128/mahatma-gandhi-icon.png',
        mealtype:'nonveg',
        extratype:'veg'
      },
      {
        id: '58694a0f-3da1-471f-bd96-14557wee29d72',
        ordernum:'1009',
        meal: 'Sheer khurma ',
        extras:'Brocolli salad',
        receiver:'Stephen Grider',
        recieverAddress:'Ontario',
        expected_time:'20:30 PM',
        status:'Cancelled',
        delivery_date:'19 Oct',
        avatar_url:'https://icons.iconarchive.com/icons/diversity-avatars/avatars/128/andy-warhol-icon.png',
        mealtype:'veg',
        extratype:'nonveg'
    
      },
      {
        id: '58695a0f-3da1-471f-bd96-145572e29d72',
        ordernum:'1803',
        meal: 'Sheer khurma ',
        extras:'Brocolli salad',
        receiver:'Stephen Grider',
        status:'Delivered',
        recieverAddress:'Pensyllvania',
        expected_time:'21:15 PM',
        delivery_date:'18 Oct',
        avatar_url:'https://icons.iconarchive.com/icons/diversity-avatars/avatars/128/barack-obama-icon.png',
        mealtype:'veg',
        extratype:'veg'
      },
      {
        id: '58794a0f-3da1-471f-bd96-145571e29d798',
        ordernum:'1010',
        meal: 'Sheer khurma ',
        extras:'Brocolli sala',
        receiver:'Stephen Grider',
        recieverAddress:'Washington Dc',
        expected_time:'21:25 PM',
        delivery_date:'18 Oct',
        status:'Delivered',
        avatar_url:'https://icons.iconarchive.com/icons/diversity-avatars/avatars/128/indian-man-icon.png',
        mealtype:'nonveg',
        extratype:'veg'
      },
]